name: flutter_wechat
description: this is  a flutter wechat app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # 屏幕适配方案 https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^1.0.2
  # 单向数据流 https://github.com/rrousselGit/provider
  provider: ^4.0.4
  # 字典持久化
  shared_preferences: ^0.5.6+3
  # 通用工具包
  common_utils: ^1.1.3
  # 数据库 https://github.com/tekartik/sqflite
  sqflite: ^1.3.0
  # 数据库-工具类 https://github.com/Jaguar-dart/jaguar_orm
  jaguar_query_sqflite: ^2.1.1
  # 路径-工具类 https://github.com/dart-lang/path
  path: ^1.6.4
  # 路由导航 https://github.com/theyakka/fluro
  fluro: ^1.6.0
  # http客户端 https://github.com/flutterchina/dio
  dio: ^3.0.9
  # JsonWebToken令牌 https://github.com/sidsbrmnn/jwt_decode
  jwt_decode: ^0.1.0
  # 获取App信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+10
  # 展示svg图片 https://github.com/dnfield/flutter_svg
  flutter_svg: ^0.17.3+1
  # 图片浏览器 https://github.com/renancaraujo/photo_view
  photo_view: ^0.9.2
  # 字母索引列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 网络图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0
  # 下拉刷新 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.5.8
  # https://github.com/flutter/plugins
  webview_flutter: ^0.3.19+9
  # webview https://github.com/dart-flitter/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.10+1
  # https://github.com/flutter/plugins
  image_picker: ^0.6.3+4
  # 图片裁剪 https://github.com/hnvn/flutter_image_cropper
  image_cropper: ^1.2.1
  # 二维码 https://github.com/lukef/qr.flutter
  qr_flutter: ^3.2.0
  # 保存相册 https://github.com/hui-z/image_gallery_saver
  image_gallery_saver: ^1.2.2
  # 权限 https://github.com/baseflowit/flutter-permission-handler
  permission_handler: ^4.4.0+hotfix.2
  # 二维码扫描 https://github.com/hetian9288/flutter_qr_reader
  flutter_qr_reader: ^1.0.3
  # 语音组件 https://github.com/yxwandroid/flutter_plugin_record
  flutter_plugin_record: ^0.1.3
  # 批量选择图片 https://github.com/Sh1d0w/multi_image_picker
  # multi_image_picker: ^4.6.4
  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^2.0.4
  # 音频播放 https://github.com/luanpotter/audioplayer
  audioplayers: ^0.14.2
  # 骨架 https://github.com/hnvn/flutter_shimmer
  shimmer: ^1.1.0
  # emoji https://github.com/JeffG05/emoji_picker
  emoji_picker: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/data/sql/
    - assets/images/icons/
    - assets/images/login/
    - assets/images/tabbar/
    - assets/images/contacts/


